title: Center for Cyber Intelligence
description: Defining the Future of Cyber Intelligence
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- jekyll-feed
- jekyll-archives

theme: midnight