title: Center for Cyber Intelligence
description: Defining the Future of Cyber Intelligence
theme: jekyll-theme-midnight
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate